version: 2.1

jobs:
  build-and-test:
    docker:
      - image: openjdk
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mvn clean install
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
